version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: /slmarta-0.0.1-SNAPSHOT.jar
    restart: always
    depends_on:
      - "db"

  db:
    image: "cassandra:latest"
    ports:
    - "9042:9042"
